In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('StudentsPerformance.csv')

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [7]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [9]:
df.shape

(1000, 8)

In [10]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [11]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [12]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [19]:
df.describe(include='all')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
count,1000,1000,1000,1000,1000,1000.00000,1000.000000,1000.000000
unique,2,5,6,2,2,NaN,NaN,NaN
top,female,group C,some college,standard,none,NaN,NaN,NaN
freq,518,319,226,645,642,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,66.08900,69.169000,68.054000
std,NaN,NaN,NaN,NaN,NaN,15.16308,14.600192,15.195657
min,NaN,NaN,NaN,NaN,NaN,0.00000,17.000000,10.000000
25%,NaN,NaN,NaN,NaN,NaN,57.00000,59.000000,57.750000
50%,NaN,NaN,NaN,NaN,NaN,66.00000,70.000000,69.000000
75%,NaN,NaN,NaN,NaN,NaN,77.00000,79.000000,79.000000
max,NaN,NaN,NaN,NaN,NaN,100.00000,100.000000,100.000000

In [20]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [21]:
df.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [22]:
type(df.gender)

pandas.core.series.Series

In [23]:
df['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [24]:
df[['gender']]

     gender
0    female
1    female
2    female
3      male
4      male
..      ...
995  female
996    male
997  female
998  female
999  female

[1000 rows x 1 columns]

In [25]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [29]:
df[(df['math score']>80) & (df['gender']=='female')]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
6,female,group B,some college,standard,completed,88,95,92
56,female,group E,associate's degree,standard,completed,82,85,86
102,female,group D,associate's degree,standard,none,85,91,89
106,female,group D,master's degree,standard,none,87,100,100
...,...,...,...,...,...,...,...,...
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
970,female,group D,bachelor's degree,standard,none,89,100,100
979,female,group C,associate's degree,standard,none,91,95,94
995,female,group E,master's degree,standard,completed,88,99,95

In [31]:
df[df['race/ethnicity'].isin(['group A','group B'])]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
983,female,group A,some college,standard,completed,78,87,91
985,male,group A,high school,standard,none,57,51,54
988,female,group A,some high school,free/reduced,none,44,45,45
991,female,group B,some high school,standard,completed,65,82,78
994,male,group A,high school,standard,none,63,63,62

In [32]:
df[(df['math score'] >= 90) & (df['math score'] <= 100)]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
34,male,group E,some college,standard,none,97,87,82
104,male,group C,some college,standard,completed,98,86,90
114,female,group E,bachelor's degree,standard,completed,99,100,100
121,male,group B,associate's degree,standard,completed,91,89,92
149,male,group E,associate's degree,free/reduced,completed,100,100,93
165,female,group C,bachelor's degree,standard,completed,96,100,100
171,male,group E,some high school,standard,none,94,88,78
179,female,group D,some high school,standard,completed,97,100,100
233,male,group E,some high school,standard,none,92,87,78
263,female,group E,high school,standard,none,99,93,90
286,male,group E,associate's degree,standard,completed,97,82,88
299,male,group D,associate's degree,free/reduced,none,90,87,75
306,male,group E,some college,standard,completed,99,87,81
333,male,group B,associate's degree,standard,none,90,78,81
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
469,male,group C,some college,standard,none,91,74,76
474,female,group B,associate's degree,standard,completed,90,90,91
501,female,group B,associate's degree,standard,completed,94,87,92
503,female,group E,associate's degree,standard,completed,95,89,92
521,female,group C,associate's degree,standard,none,91,86,84
539,male,group A,associate's degree,standard,completed,97,92,86
546,female,group A,some high school,standard,completed,92,100,97
562,male,group C,bachelor's degree,standard,completed,96,90,92
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
571,male,group A,bachelor's degree,standard,none,91,96,92
594,female,group C,bachelor's degree,standard,completed,92,100,99
612,male,group C,bachelor's degree,standard,completed,94,90,91
618,male,group D,master's degree,standard,none,95,81,84
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
659,male,group D,associate's degree,standard,none,90,87,85
685,female,group E,master's degree,standard,completed,94,99,100
689,male,group E,some college,free/reduced,none,93,90,83
710,male,group C,some college,standard,completed,93,84,90
712,female,group D,some college,standard,none,98,100,99
717,female,group C,associate's degree,standard,completed,96,96,99
719,male,group E,associate's degree,free/reduced,completed,91,73,80
736,male,group C,associate's degree,standard,none,92,79,84
779,male,group E,associate's degree,standard,completed,94,85,82
784,male,group C,bachelor's degree,standard,completed,91,81,79
808,male,group C,high school,standard,none,90,75,69
815,male,group B,some high school,standard,completed,94,86,87
845,male,group E,master's degree,standard,none,90,85,84
846,male,group C,master's degree,standard,completed,91,85,85
855,female,group B,bachelor's degree,standard,none,97,97,96
864,male,group C,associate's degree,standard,none,97,93,91
873,male,group E,associate's degree,free/reduced,none,90,90,82
886,female,group E,associate's degree,standard,completed,93,100,95
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
919,male,group B,some college,standard,completed,91,96,91
934,male,group C,associate's degree,standard,completed,98,87,90
950,male,group E,high school,standard,none,94,73,71
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
979,female,group C,associate's degree,standard,none,91,95,94

In [33]:
df[df['math score'].between(90,100)]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
34,male,group E,some college,standard,none,97,87,82
104,male,group C,some college,standard,completed,98,86,90
114,female,group E,bachelor's degree,standard,completed,99,100,100
121,male,group B,associate's degree,standard,completed,91,89,92
149,male,group E,associate's degree,free/reduced,completed,100,100,93
165,female,group C,bachelor's degree,standard,completed,96,100,100
171,male,group E,some high school,standard,none,94,88,78
179,female,group D,some high school,standard,completed,97,100,100
233,male,group E,some high school,standard,none,92,87,78
263,female,group E,high school,standard,none,99,93,90
286,male,group E,associate's degree,standard,completed,97,82,88
299,male,group D,associate's degree,free/reduced,none,90,87,75
306,male,group E,some college,standard,completed,99,87,81
333,male,group B,associate's degree,standard,none,90,78,81
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
469,male,group C,some college,standard,none,91,74,76
474,female,group B,associate's degree,standard,completed,90,90,91
501,female,group B,associate's degree,standard,completed,94,87,92
503,female,group E,associate's degree,standard,completed,95,89,92
521,female,group C,associate's degree,standard,none,91,86,84
539,male,group A,associate's degree,standard,completed,97,92,86
546,female,group A,some high school,standard,completed,92,100,97
562,male,group C,bachelor's degree,standard,completed,96,90,92
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
571,male,group A,bachelor's degree,standard,none,91,96,92
594,female,group C,bachelor's degree,standard,completed,92,100,99
612,male,group C,bachelor's degree,standard,completed,94,90,91
618,male,group D,master's degree,standard,none,95,81,84
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
659,male,group D,associate's degree,standard,none,90,87,85
685,female,group E,master's degree,standard,completed,94,99,100
689,male,group E,some college,free/reduced,none,93,90,83
710,male,group C,some college,standard,completed,93,84,90
712,female,group D,some college,standard,none,98,100,99
717,female,group C,associate's degree,standard,completed,96,96,99
719,male,group E,associate's degree,free/reduced,completed,91,73,80
736,male,group C,associate's degree,standard,none,92,79,84
779,male,group E,associate's degree,standard,completed,94,85,82
784,male,group C,bachelor's degree,standard,completed,91,81,79
808,male,group C,high school,standard,none,90,75,69
815,male,group B,some high school,standard,completed,94,86,87
845,male,group E,master's degree,standard,none,90,85,84
846,male,group C,master's degree,standard,completed,91,85,85
855,female,group B,bachelor's degree,standard,none,97,97,96
864,male,group C,associate's degree,standard,none,97,93,91
873,male,group E,associate's degree,free/reduced,none,90,90,82
886,female,group E,associate's degree,standard,completed,93,100,95
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
919,male,group B,some college,standard,completed,91,96,91
934,male,group C,associate's degree,standard,completed,98,87,90
950,male,group E,high school,standard,none,94,73,71
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
979,female,group C,associate's degree,standard,none,91,95,94

In [34]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [35]:
df.loc[0:5, ['gender', 'math score']]

   gender  math score
0  female          72
1  female          69
2  female          90
3    male          47
4    male          76
5  female          71

In [36]:
df.loc[:100,['gender', 'math score', 'reading score']]

     gender  math score  reading score
0    female          72             72
1    female          69             90
2    female          90             95
3      male          47             57
4      male          76             78
..      ...         ...            ...
96     male          65             66
97   female          63             72
98   female          58             67
99   female          65             67
100    male          79             67

[101 rows x 3 columns]

In [41]:
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [38]:
df.iloc[5:10,[2,3]]

  parental level of education         lunch
5          associate's degree      standard
6                some college      standard
7                some college  free/reduced
8                 high school  free/reduced
9                 high school  free/reduced

In [40]:
df.loc[5:10,['gender']]

    gender
5   female
6   female
7     male
8     male
9   female
10    male

In [42]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [43]:
df['averagescore'] = (df['math score'] + df['reading score'] + df['writing score']) / 3

In [44]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667
1,female,group C,some college,standard,completed,69,90,88,82.333333
2,female,group B,master's degree,standard,none,90,95,93,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333
4,male,group C,some college,standard,none,76,78,75,76.333333
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000
996,male,group C,high school,free/reduced,none,62,55,55,57.333333
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000
998,female,group D,some college,standard,completed,68,78,77,74.333333
999,female,group D,some college,free/reduced,none,77,86,86,83.000000

In [47]:
def math_performance(score):
    if score['math score'] >= 60:
        return 'good'
    elif score['math score'] >= 40:
        return 'average'
    else:
        return 'poor'

df['math_perfrmance'] = df.apply(math_performance, axis=1)

In [48]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore,math_perfrmance
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,good
1,female,group C,some college,standard,completed,69,90,88,82.333333,good
2,female,group B,master's degree,standard,none,90,95,93,92.666667,good
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,average
4,male,group C,some college,standard,none,76,78,75,76.333333,good
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000,good
996,male,group C,high school,free/reduced,none,62,55,55,57.333333,good
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000,average
998,female,group D,some college,standard,completed,68,78,77,74.333333,good
999,female,group D,some college,free/reduced,none,77,86,86,83.000000,good

In [49]:
def newCol(score):
   return  score['race/ethnicity'].replace('group ','') 
df['newCol'] = df.apply(lambda score: newCol(score), axis=1)  
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore,math_perfrmance,newCol
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,good,B
1,female,group C,some college,standard,completed,69,90,88,82.333333,good,C
2,female,group B,master's degree,standard,none,90,95,93,92.666667,good,B
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,average,A
4,male,group C,some college,standard,none,76,78,75,76.333333,good,C

In [50]:
df['race_short'] = df['race/ethnicity'].str.replace('group ', '', case=False)

In [51]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore,math_perfrmance,newCol,race_short
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,good,B,B
1,female,group C,some college,standard,completed,69,90,88,82.333333,good,C,C
2,female,group B,master's degree,standard,none,90,95,93,92.666667,good,B,B
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,average,A,A
4,male,group C,some college,standard,none,76,78,75,76.333333,good,C,C

In [52]:
def getGroups(row):
   l =  row['race/ethnicity']
   return l[:1]
df['group'] = df.apply(getGroups, axis=1)
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore,math_perfrmance,newCol,race_short,group
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,good,B,B,g
1,female,group C,some college,standard,completed,69,90,88,82.333333,good,C,C,g
2,female,group B,master's degree,standard,none,90,95,93,92.666667,good,B,B,g
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,average,A,A,g
4,male,group C,some college,standard,none,76,78,75,76.333333,good,C,C,g

In [53]:
def Group(group):
    if group['race/ethnicity'] == 'group A':
        return 'A'
    elif group['race/ethnicity'] == 'group B':
        return 'B'
    else:
        return 'C'
    
df['group'] = df.apply(Group, axis=1)

In [54]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore,math_perfrmance,newCol,race_short,group
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,good,B,B,B
1,female,group C,some college,standard,completed,69,90,88,82.333333,good,C,C,C
2,female,group B,master's degree,standard,none,90,95,93,92.666667,good,B,B,B
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,average,A,A,A
4,male,group C,some college,standard,none,76,78,75,76.333333,good,C,C,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000,good,E,E,C
996,male,group C,high school,free/reduced,none,62,55,55,57.333333,good,C,C,C
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000,average,C,C,C
998,female,group D,some college,standard,completed,68,78,77,74.333333,good,D,D,C
999,female,group D,some college,free/reduced,none,77,86,86,83.000000,good,D,D,C

In [56]:
def getGroups(row):
   l =  row['race/ethnicity'].split(' ')
   return l[1]
df['group'] = df.apply(getGroups, axis=1)
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore,math_perfrmance,newCol,race_short,group
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,good,B,B,B
1,female,group C,some college,standard,completed,69,90,88,82.333333,good,C,C,C
2,female,group B,master's degree,standard,none,90,95,93,92.666667,good,B,B,B
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,average,A,A,A
4,male,group C,some college,standard,none,76,78,75,76.333333,good,C,C,C
5,female,group B,associate's degree,standard,none,71,83,78,77.333333,good,B,B,B
6,female,group B,some college,standard,completed,88,95,92,91.666667,good,B,B,B
7,male,group B,some college,free/reduced,none,40,43,39,40.666667,average,B,B,B
8,male,group D,high school,free/reduced,completed,64,64,67,65.000000,good,D,D,D
9,female,group B,high school,free/reduced,none,38,60,50,49.333333,poor,B,B,B

In [58]:
df['gender_num'] = df['gender'].map({'female': 1,'male': 0})

In [59]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore,math_perfrmance,newCol,race_short,group,gender_num
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,good,B,B,B,1
1,female,group C,some college,standard,completed,69,90,88,82.333333,good,C,C,C,1
2,female,group B,master's degree,standard,none,90,95,93,92.666667,good,B,B,B,1
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,average,A,A,A,0
4,male,group C,some college,standard,none,76,78,75,76.333333,good,C,C,C,0

In [61]:
df['racecat'] = df['race/ethnicity'].map({'group A': "A", 'group B': "B", 'group C': "C", 'group D': "D", 'group E': "E"})

In [62]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore,math_perfrmance,newCol,race_short,group,gender_num,racecat
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,good,B,B,B,1,B
1,female,group C,some college,standard,completed,69,90,88,82.333333,good,C,C,C,1,C
2,female,group B,master's degree,standard,none,90,95,93,92.666667,good,B,B,B,1,B
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,average,A,A,A,0,A
4,male,group C,some college,standard,none,76,78,75,76.333333,good,C,C,C,0,C

In [63]:
df['gender'].unique()

array(['female', 'male'], dtype=object)

In [64]:
df['gender'].nunique()

2

In [65]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore,math_perfrmance,newCol,race_short,group,gender_num,racecat
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,good,B,B,B,1,B
1,female,group C,some college,standard,completed,69,90,88,82.333333,good,C,C,C,1,C
2,female,group B,master's degree,standard,none,90,95,93,92.666667,good,B,B,B,1,B
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,average,A,A,A,0,A
4,male,group C,some college,standard,none,76,78,75,76.333333,good,C,C,C,0,C

In [66]:
df.sort_values(by='math score', ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore,math_perfrmance,newCol,race_short,group,gender_num,racecat
962,female,group E,associate's degree,standard,none,100,100,100,100.000000,good,E,E,E,1,E
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000,good,E,E,E,1,E
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667,good,E,E,E,0,E
625,male,group D,some college,standard,completed,100,97,99,98.666667,good,D,D,D,0,D
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000,good,E,E,E,0,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333,poor,C,C,C,1,C
787,female,group B,some college,standard,none,19,38,32,29.666667,poor,B,B,B,1,B
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000,poor,B,B,B,1,B
980,female,group B,high school,free/reduced,none,8,24,23,18.333333,poor,B,B,B,1,B
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000,poor,C,C,C,1,C

In [67]:
pd.pivot_table(df,
               values='math score',
               index='gender',
               columns='lunch',
               aggfunc='mean'
               
               )

lunch   free/reduced   standard
gender
female     55.814815  68.124620
male       62.457831  72.022152

In [68]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,averagescore,math_perfrmance,newCol,race_short,group,gender_num,racecat
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,good,B,B,B,1,B
1,female,group C,some college,standard,completed,69,90,88,82.333333,good,C,C,C,1,C
2,female,group B,master's degree,standard,none,90,95,93,92.666667,good,B,B,B,1,B
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,average,A,A,A,0,A
4,male,group C,some college,standard,none,76,78,75,76.333333,good,C,C,C,0,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000,good,E,E,E,1,E
996,male,group C,high school,free/reduced,none,62,55,55,57.333333,good,C,C,C,0,C
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000,average,C,C,C,1,C
998,female,group D,some college,standard,completed,68,78,77,74.333333,good,D,D,D,1,D
999,female,group D,some college,free/reduced,none,77,86,86,83.000000,good,D,D,D,1,D

In [69]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'averagescore', 'math_perfrmance', 'newCol',
       'race_short', 'group', 'gender_num', 'racecat'],
      dtype='object')

In [70]:
df.drop(columns=['averagescore', 'math_perfrmance', 'newCol', 'race_short', 'group', 'gender_num', 'racecat'], inplace=True)

In [71]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [72]:
df.drop(index=[0,1,2], inplace=True)

In [73]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [74]:
df['math score'].dtype

dtype('int64')

In [75]:
df['math score'].astype('float64')

3      47.0
4      76.0
5      71.0
6      88.0
7      40.0
       ...
995    88.0
996    62.0
997    59.0
998    68.0
999    77.0
Name: math score, Length: 997, dtype: float64